/**
 * Phantom player personality profiles.
 *
 * Each profile defines a distinct player persona — identity, play style,
 * social behavior, and timing. These govern all phantom behavior so no two
 * phantoms feel the same.
 */

export const PROFILES = [
  {
    username: 'kingMe42',
    email: 'kingme42@pm.me',
    password: 'Km42!xSecure',
    skill: 2,
    moveSpeed: 'normal',
    playStyle: 'aggressive',
    resignThreshold: -15,
    chattiness: 0.6,
    reactivity: 0.8,
    tone: 'friendly',
    sessionLength: [20, 40],
    breakLength: [8, 20],
    actionDelay: [8, 18],
    readyDelay: [2, 4],
  },
  {
    username: 'checkerChamp',
    email: 'cchamp@pm.me',
    password: 'Cc99!zSecure',
    skill: 3,
    moveSpeed: 'slow',
    playStyle: 'defensive',
    resignThreshold: -15,
    chattiness: 0.3,
    reactivity: 0.5,
    tone: 'competitive',
    sessionLength: [25, 45],
    breakLength: [10, 25],
    actionDelay: [12, 25],
    readyDelay: [3, 6],
  },
  {
    username: 'jumpMaster',
    email: 'jumpmaster@pm.me',
    password: 'Jm77!wSecure',
    skill: 1,
    moveSpeed: 'fast',
    playStyle: 'aggressive',
    resignThreshold: -18,
    chattiness: 0.8,
    reactivity: 0.9,
    tone: 'troll',
    sessionLength: [15, 30],
    breakLength: [5, 15],
    actionDelay: [5, 12],
    readyDelay: [1, 3],
  },
  {
    username: 'redSideFTW',
    email: 'redside@pm.me',
    password: 'Rs55!vSecure',
    skill: 3,
    moveSpeed: 'normal',
    playStyle: 'balanced',
    resignThreshold: -20,
    chattiness: 0.4,
    reactivity: 0.7,
    tone: 'chill',
    sessionLength: [30, 50],
    breakLength: [10, 30],
    actionDelay: [10, 22],
    readyDelay: [2, 5],
  },
  {
    username: 'boardWiz',
    email: 'boardwiz@pm.me',
    password: 'Bw88!uSecure',
    skill: 4,
    moveSpeed: 'slow',
    playStyle: 'defensive',
    resignThreshold: -Infinity,
    chattiness: 0.2,
    reactivity: 0.4,
    tone: 'competitive',
    sessionLength: [20, 35],
    breakLength: [15, 30],
    actionDelay: [15, 30],
    readyDelay: [3, 6],
  },
  {
    username: 'doubleJump99',
    email: 'dj99@pm.me',
    password: 'Dj99!tSecure',
    skill: 2,
    moveSpeed: 'fast',
    playStyle: 'aggressive',
    resignThreshold: -12,
    chattiness: 0.7,
    reactivity: 0.85,
    tone: 'friendly',
    sessionLength: [15, 35],
    breakLength: [5, 15],
    actionDelay: [6, 14],
    readyDelay: [1, 3],
  },
  {
    username: 'queenPromo',
    email: 'queenpromo@pm.me',
    password: 'Qp44!sSecure',
    skill: 3,
    moveSpeed: 'normal',
    playStyle: 'balanced',
    resignThreshold: -14,
    chattiness: 0.5,
    reactivity: 0.6,
    tone: 'friendly',
    sessionLength: [20, 40],
    breakLength: [8, 20],
    actionDelay: [8, 20],
    readyDelay: [2, 5],
  },
  {
    username: 'cornerKing',
    email: 'cornerking@pm.me',
    password: 'Ck33!rSecure',
    skill: 1,
    moveSpeed: 'slow',
    playStyle: 'defensive',
    resignThreshold: -20,
    chattiness: 0.9,
    reactivity: 0.7,
    tone: 'troll',
    sessionLength: [10, 25],
    breakLength: [10, 20],
    actionDelay: [8, 16],
    readyDelay: [2, 4],
  },
  {
    username: 'slideDiag',
    email: 'slidediag@pm.me',
    password: 'Sd22!qSecure',
    skill: 2,
    moveSpeed: 'normal',
    playStyle: 'balanced',
    resignThreshold: -10,
    chattiness: 0.35,
    reactivity: 0.75,
    tone: 'chill',
    sessionLength: [20, 40],
    breakLength: [8, 20],
    actionDelay: [10, 20],
    readyDelay: [2, 5],
  },
  {
    username: 'capturKing',
    email: 'capturking@pm.me',
    password: 'Ck11!pSecure',
    skill: 4,
    moveSpeed: 'fast',
    playStyle: 'aggressive',
    resignThreshold: -18,
    chattiness: 0.45,
    reactivity: 0.65,
    tone: 'competitive',
    sessionLength: [25, 45],
    breakLength: [10, 25],
    actionDelay: [8, 18],
    readyDelay: [1, 3],
  },
];

/** Move speed ranges in milliseconds [min, max] */
export const MOVE_SPEEDS = {
  fast:   [1000, 2000],
  normal: [2000, 4000],
  slow:   [3000, 6000],
};

/** Uniform random in [min, max] */
export function rand(min, max) {
  return min + Math.random() * (max - min);
}

/** Uniform random integer in [min, max] inclusive */
export function randInt(min, max) {
  return Math.floor(rand(min, max + 1));
}
