// Editorial explanations shared by generated drafts. These describe this site's
// rules and a way to examine a tactic; they do not certify a particular outcome.
export const THEME_TEXT = Object.freeze({
  'multi-jump': 'A multi-jump lets one piece capture several opponents in a single turn. Follow every landing square before choosing the first jump: removing a piece can open a new diagonal or make a backward capture available. Men may capture backward, and flying kings may have several landing choices beyond an enemy piece. A capture must continue while another jump is available, except that crowning ends the turn. You may choose among legal branches; you do not have to take the branch with the most captures. Compare the complete routes, the pieces removed and the safety of the final square.',
  shot: 'A shot uses a sacrifice to change the arrangement of the opposing pieces. Offering a capture can draw a defender away, clear a diagonal or place a target where a second piece can reach it. Captures are compulsory, but that does not mean the opponent must take the particular piece you offered: another capture or another branch may be available. Check every legal reply before calling a sacrifice forced. Then follow your intended recapture to its final landing. Count what both sides have given up, and check for crowning or another compulsory capture before deciding whether the combination has paid off.',
  breakthrough: 'A breakthrough brings a man to the far row and crowns it as a king. The new king can move along open diagonals in either direction and capture from a distance, which can change the position substantially. Crowning alone does not guarantee a win: the king may face an immediate capture, or the opponent may have active kings of their own. Look for a clear route to the promotion row, then inspect the reply from the resulting board. On this site crowning ends the turn, including a capture chain. A newly crowned piece cannot continue jumping until a later turn.',
  'king-trap': 'A flying king can cross an open diagonal, but its movement still depends on which squares are occupied. A trap restricts those choices or uses a compulsory capture to bring the king into range of another piece. Inspect every landing beyond the captured piece: a king may be able to stop on several different squares. Offering one attractive capture does not establish a trap if another legal route escapes. Follow each relevant branch and check which piece makes the final capture. Removing a king can be valuable, but compare the remaining men, kings and legal moves before judging the resulting position.',
  immobilise: 'A player with no legal move loses, even if pieces remain on the board. To check an immobilisation, examine the whole opposing position after your move. Men step forward but can capture in either direction, so blocking their forward steps is not enough when a backward jump remains. Kings can use distant open squares, and a capture may let one escape an apparent enclosure. Check every piece for both ordinary moves and captures. The winning move may close a gap or remove the last mobile piece. Only an empty set of legal replies establishes an immediate win by immobilisation.',
  'quiet-move': 'A quiet move changes the position without taking a piece. It can prepare a capture, improve a landing square, protect a route to promotion or offer a sacrifice. First check that no capture is available, since captures are compulsory on this site. Then examine the opponent\'s replies instead of assuming that your threat will be ignored. A move that works against one reply may fail against another. In these puzzles, the verified line shows the selected defence and the tactical gain that follows. Compare the resulting board with the starting position, including kings and possible recaptures, rather than counting only the first piece won.'
});
